### ISSUE TITLE
Reduce the checks inside main from scan.c

### ISSUE THREAD

**Issue by xPandoraa** [J-joao/pattern-scanning#1]
Inside scan.c, you can reduce the code from:

if (argc < 3) {
        printf("Incorrect usage!\n");
        return EXIT_FAILURE;
    }
    if (argc > 3) {
        printf("Incorrect usage!\n");
        return EXIT_FAILURE;
}
to:

if (argc != 3) {
        printf("Incorrect usage!\n");
        return EXIT_FAILURE;
   }

This will make your code faster.

**Comment by J-joao** [comment]
thank you for the advice, I'll change it!
